// <auto-generated />
namespace Lab1Week11.Migrations.ClubMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class datesnulled : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datesnulled));
        
        string IMigrationMetadata.Id
        {
            get { return "201712081056258_dates-nulled"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
